README.md, psgo.go
Change the minimal tab width of the psgo sample implementation from
20 (as docker-top) to 5 (easier to read on normal-sized terminals).
=> psgo: change minimal tab width

.travis.yml, Makefile, test/format.bats, test/pid.bats
Add integration tests to enable a more thorough testing.  All
integration tests are located under ./test and are implemented with
bats.
=> add integration tests

ps/capabilities.go, ps/ps.go, test/format.bats, test/pid.bats
Add four format descriptors (capinh, capprm, capeff, capbnd) to allow
parsing the four sets of capabilities.
Fixes: #11
=> support capabilities

ps/ps.go, test/format.bats, test/pid.bats
Add a `seccomp` format descriptor which prints the seccomp mode of the
corresponding process (i.e., "disabled", "strict" or "fitler").
Fixes: #12
=> support seccomp

ps/ps.go, psgo.go, test/list.bats
Add a new API `ListDescriptors() []string` returning a string slice of
all supported AIX format descriptors in the normal form.  Users of psgo
can use this API to explore supported descriptors (e.g., for the purpose
of bash completion).
=> list descriptors

ps/ps.go
Others might want to parse our ouput with space separation, so remove
spaces between caps, also uses less line space.
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
=> Don't add a space between caps.

README.md, psgo.go, sample/sample.go
Change the API arguments from `string` to `[]string` and the return
values from `[]string` to `[][]string` to give users more control over
the data.  This way, users can, for instance, apply filters on the
processes' data.
=> make API slice based

README.md, psgo.go, test/format.bats, test/list.bats, test/pid.bats
This is needed to mimic `ps -ex` output.
Signed-off-by: Marco Vedovati <mvedovati@suse.com>
=> Add process state format descriptor

internal/proc/status.go
"should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)"
=> fix golint error

README.md, psgo.go, test/format.bats, test/list.bats, test/pid.bats
- Add the ambient capabilities descriptor
- Rename capabilities headers from "CAPABILITIES" to a unambiguos name (CAPEFFECTIVE, CAPPERMITTED, CAPBOUNDING, CAPINHERITHED, CAPAMBIENT).
Updated tests and docs as well.
=> Capabilities: add ambient descriptor + unambiguos headers

internal/proc/ns.go, internal/proc/ns_test.go, internal/proc/status.go, internal/proc/status_test.go, internal/process/process.go, internal/process/process_test.go, internal/types/types.go, psgo.go, test/pid.bats
When a given PID is in a different user namespace, extract
/proc/$pid/status from that namespace to return the correct
user and group of the corresponding processes.
Fixes: #35
=> support user namespaces

Makefile, README.md, psgo.go, sample/sample.go, test/pids.bats
ProcessInfoByPids API is used to to retrieve process information from a list of user specified processes. 
The sample application has been updated to use it as an option.
Implements #32
=> Add ProcessInfoByPids API

README.md, psgo.go, sample/sample.go, test/join.bats
Add a new API, `JoinNamespaceAndProcessInfoByPids`, which is similar to
`JoinNamespaceAndProcessInfo` but takes a slice of pids as an argument.
To avoid duplicate entries (e.g., when two or more containers share the
same PID namespace), a given PID namespace will be joined only once.
Notice that the CLI of the sample implementation in `./bin/psgo` has
changed.  The `-pid` flag has been removed in favor of the`-pids` flag.
A new `-join` bool flag controls if the namespaces of the provided pids
shall be joined.
=> add `JoinNamespaceAndProcessInfoByPids` API

internal/capabilities/capabilities.go, internal/dev/tty.go, internal/dev/tty_test.go, internal/host/host.go, internal/host/host_test.go, internal/proc/attr.go, internal/proc/attr_test.go, internal/proc/cmdline.go, internal/proc/cmdline_test.go, internal/proc/ns.go, internal/proc/ns_test.go, internal/proc/pids.go, internal/proc/pids_test.go, internal/proc/stat.go, internal/proc/stat_test.go, internal/proc/status.go, internal/proc/status_test.go, internal/process/process.go, internal/process/process_test.go, internal/types/types.go, psgo.go, psgo_test.go
Fully apply the Apache license (version 2.0) by adding the corresponding
boilerplate copyright header to each psgo source file.  The copyright
owner is "psgo authors".
Fixes: #42
=> add copyright header

psgo.go
Some times process will exit before we can read
their data.  We should ignore these processes if
they get ENOENT.  Also we need to unwrap errors
to make sure we check against unwrapped errors.
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
=> Fix race condition on processes dieing

internal/process/process.go
Use errors.Cause(...) to unwrap the error and examine the cause.
=> Fix another race-condition when a PID has died

.travis.yml, Makefile
`make validate` will always fetch the latest version of golangci-lint.
=> switch to golangci-lint

psgo.go
s/ErrUnkownDescriptor/ErrUnknownDescriptor/
I consider this a bug fix.
=> fix ErrUnkownDescriptor typo

.travis.yml, Makefile, internal/proc/ns.go, internal/process/process.go, psgo.go, sample/sample.go, test/join.bats
add support for running in a user namespace so that `podman top -l huser` works correctly for rootless containers.
Once this lands, the patch for podman is trivial:
```diff
diff --git a/libpod/container_top_linux.go b/libpod/container_top_linux.go
index 392a7029..0f6706d4 100644
--- a/libpod/container_top_linux.go
+++ b/libpod/container_top_linux.go
@@ -6,6 +6,7 @@ import (
"strconv"
"strings"
+       "github.com/containers/libpod/pkg/rootless"
"github.com/containers/psgo"
"github.com/pkg/errors"
)
@@ -47,7 +48,14 @@ func (c *Container) GetContainerPidInformation(descriptors []string) ([]string,
//       filters on the data.  We need to change the API here and the
//       varlink API to return a [][]string if we want to make use of
//       filtering.
-       psgoOutput, err := …
```
=> psgo: add support for running in a namespace

internal/host/host.go, internal/host/host_test.go, internal/process/process.go
read AT_CLKTCK directly from the auxv vector, so it is possible to use
psgo without requiring cgo.
This is what internally sysconf does, although it doesn't use
/proc/self/auxv but read directly from memory.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> process: read AT_CLKTCK from the auxv

Makefile, internal/host/host.go, internal/host/host_cgo.go, internal/host/host_nocgo.go
revert partially the previous commit and use /proc/self/auxv only when
cgo is not available.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> host: use /proc/self/auxv only when not using cgo

.travis.yml, Makefile, test/join.bats
Go 1.13.x isn't sensitive to the `GO111MODULE` environment variable
causing `make binary-local` to not use the vendored sources in
`./vendor`.  Force builds of module-supporting go versions to use the
vendored sources by setting `-mod=vendor`.
Verified in a `fedora:rawhide` container.
=> go build: use `-mod=vendor` for go >= 1.11.x

README.md, internal/process/process.go, psgo.go, test/format.bats, test/list.bats
Fixes: #61
@rhatdan @haircommander @giuseppe PTAL
=> add `stime` descriptor to extract process start times

Makefile, hack/install_golangci.sh, internal/process/process.go
Moreover, we really just need to run `golangci-lint` since it already
includes `gofmt`, `govet` and dozens of other linters.
=> make validate: don't eat golangci reports

internal/proc/stat.go, internal/proc/stat_test.go, internal/process/process.go
Parsing the command name properly requires some effort: we
need to determine the slice between the first ( and the last(!) )
in order to support command names which contain white space or closing
parentheses.
Fixes #66.
=> internal/proc: parse /proc/$PID/stat correctly

psgo.go, psgo_test.go
This is the field that ps(1) classically uses, also verified against
procps-ng-3.3.15.
Fixes #65.
=> psgo: use Stat.Comm in processCOMM

internal/dev/tty.go
Rdev is uint32 on mips so we have to typecast to uint64 in that case.
see: https://github.com/golang/go/blob/c9fb4eb0a22131cc9922fa96afba01d4e21d4fd4/src/syscall/ztypes_linux_mips.go#L104
Fixes #76
=> Fix build for mips architecture

vendor.conf
It survived long without being noticed. Hiding in the git tree.
=> rm vendor.conf

README.md, psgo.go, test/format.bats, test/list.bats
Add two new descriptors:
* `groups` for supplementary groups inside the container
* `hgroups` for the counterpart on the host
Example:
```
podman (main) $ ./bin/podman top -l pid,hpid,group,hgroup,groups,hgroups
PID         HPID        GROUP       HGROUP      GROUPS                                                        HGROUPS
1           92536       root        1000        root,bin,daemon,sys,adm,disk,wheel,floppy,dialout,tape,video  1000,100000,100001,100002,100003,100005,100009,100010,100019,100025,100026
```
Closes: #87
@rhatdan @giuseppe PTAL
=> support supplementary groups

README.md, psgo.go, test/format.bats, test/list.bats
Add two descriptors:
- `uid` prints the effective UID of the process as the decimal representation
- `huid` prints the corresponding host UID of a container process
Example:
```
$ ./bin/podman top 67 pid,hpid,user,uid,huid
PID         HPID        USER        UID         HUID
1           5155        root        0           1000
```
Closes: [#16009](https://github.com/containers/podman/issues/16009)
Signed-off-by: Piotr Resztak <piotr.resztak@gmail.com>
@rhatdan @vrothberg
=> Add uid,huid descriptors

internal/proc/attr.go, internal/process/process.go, psgo.go
for /proc/$PID/cmdline, the kernel could return ESRCH instead of ENOENT if the target process is terminated between the opening of the "cmdline" file and reading from it.
Handle ESRCH in the same way as ENOENT when reading from the proc file system.
=> psgo: handle ESRCH as ENOENT
